'use strict';
const fs=require('fs'), fsp=require('fs/promises'), os=require('os'), path=require('path');
const readline=require('readline/promises'), {execFile}=require('child_process'), {promisify}=require('util');
const exec=promisify(execFile), VERSION='1.2.2';
const dataDir=path.join(process.env.LOCALAPPDATA||os.homedir(),'MyG Print Connector');
const configPath=path.join(dataDir,'config.json'), authMarkerPath=path.join(dataDir,'reauthorization-required'), helperPath=path.join(dataDir,'raw-print.ps1');
let config, printerName=null, stopping=false, lastHeartbeat=0;
const args=process.argv.slice(2);
function arg(name){const index=args.indexOf(name);return index>=0?args[index+1]:null}
async function detectPrinters(){const s="Get-Printer | Where-Object {$_.Type -eq 'Local'} | Select-Object -ExpandProperty Name | ConvertTo-Json -Compress";const {stdout}=await exec('powershell.exe',['-NoProfile','-Command',s],{windowsHide:true,timeout:15000});if(!stdout.trim())return[];const v=JSON.parse(stdout.trim());return(Array.isArray(v)?v:[v]).map(String).filter(Boolean)}
async function api(endpoint,body={},auth=true){const response=await fetch(`${config.apiUrl}${endpoint}`,{method:'POST',headers:{'content-type':'application/json',...(auth?{'x-print-agent-token':config.token}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(20000)});const data=await response.json().catch(()=>({}));if(!response.ok||!data.ok){const error=new Error(data.message||`HTTP ${response.status}`);error.status=response.status;throw error}return data.data}
async function installHelper(){await fsp.mkdir(dataDir,{recursive:true});if(fs.existsSync(helperPath))return;const source=path.join(__dirname,'raw-print.ps1');if(path.resolve(source)!==path.resolve(helperPath))await fsp.copyFile(source,helperPath)}
async function firstSetup(){let apiUrl=arg('--api-url'),code=arg('--pair-code');if(!apiUrl||!code){const rl=readline.createInterface({input:process.stdin,output:process.stdout});console.log('\nMyG Print Connector - vinculacion inicial\n');const defaultUrl=process.env.PRINT_API_URL||'http://localhost:3000/api/printing';apiUrl=(await rl.question(`Servidor [${defaultUrl}]: `)).trim()||defaultUrl;code=(await rl.question('Codigo mostrado en el sistema web: ')).trim();rl.close()}config={apiUrl:String(apiUrl).replace(/\/+$/,'')};const result=await api('/agent/pair',{code,computer_name:os.hostname(),printers:await detectPrinters(),version:VERSION},false);config={apiUrl:config.apiUrl,token:result.token,agentId:result.agentId,siteId:result.siteId};await fsp.writeFile(configPath,JSON.stringify(config,null,2));await fsp.unlink(authMarkerPath).catch(()=>{});printerName=result.printerName||null;console.log('Equipo vinculado. La impresora se administra desde MyG.')}
async function printRaw(payload,id){if(!printerName)throw new Error('No hay una impresora seleccionada.');const temp=path.join(os.tmpdir(),`myg-print-${id}-${Date.now()}.prn`);const bytes=payload.startsWith('BASE64:')?Buffer.from(payload.slice(7),'base64'):Buffer.from(payload,'ascii');await fsp.writeFile(temp,bytes);try{await exec('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',helperPath,'-PrinterName',printerName,'-FilePath',temp],{windowsHide:true,timeout:30000})}finally{await fsp.unlink(temp).catch(()=>{})}}
async function heartbeat(){if(Date.now()-lastHeartbeat<30000)return;const data=await api('/agent/heartbeat',{printers:await detectPrinters(),version:VERSION});printerName=data.agent.printerName;lastHeartbeat=Date.now()}
async function processNext(){await heartbeat();if(!printerName)return;const job=await api('/agent/claim');if(!job)return;try{await printRaw(job.payload,job.id);await api(`/agent/jobs/${job.id}/complete`,{success:true});console.log(`Trabajo #${job.id} enviado a ${printerName}.`)}catch(error){const message=error.message||String(error);await api(`/agent/jobs/${job.id}/complete`,{success:false,error:message}).catch(()=>{});console.error(`Trabajo #${job.id}: ${message}`)}}
async function main(){await installHelper();if(fs.existsSync(configPath)&&!arg('--pair-code'))config=JSON.parse(await fsp.readFile(configPath,'utf8'));else await firstSetup();if(args.includes('--pair-only'))return;console.log(`MyG Print Connector ${VERSION} activo en ${os.hostname()}.`);while(!stopping){try{await processNext()}catch(error){if(error.status===401||error.status===403){await fsp.writeFile(authMarkerPath,new Date().toISOString());console.error('La vinculacion vencio. Abre Impresion > Configurar, genera un codigo nuevo y ejecuta nuevamente el instalador.');break}console.error(`[${new Date().toISOString()}] ${error.message||error}`)}await new Promise(r=>setTimeout(r,3000))}}
process.on('SIGINT',()=>{stopping=true});process.on('SIGTERM',()=>{stopping=true});main().catch(error=>{console.error(error.message||error);process.exitCode=1});
